[package]
name = "superposition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dfdx = "0.9.0"
rand = "0.8.5"
lazy-pbar = "0.2.0"
colored = "2"
toml = "0.5.9"

[build-dependencies]
toml = "0.5.9"